name:        http-download
version:     0.2.1.0
synopsis:    Verified downloads with retries
category:    Development
author:      Michael Snoyman
maintainer:  michael@snoyman.com
copyright:   2018-2023 FP Complete
license:     BSD3
github:      commercialhaskell/http-download
description: Higher level HTTP download APIs include verification of content and retries
extra-source-files:
- ChangeLog.md

dependencies:
- base >=4.10 && < 5
- crypton
- http-client
- path
- path-io
- retry
- rio
- rio-prettyprint

library:
  source-dirs: src/
  dependencies:
  - base64-bytestring
  - bytestring
  - conduit
  - conduit-extra
  - crypton-conduit
  - directory
  - exceptions
  - filepath
  - http-conduit
  - http-types
  - memory

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - http-download
    - hspec
    - hspec-discover
