spec-version: 0.36.0

name: http-download
version: 0.2.2.0
synopsis: Verified downloads with retries
category: Development
author: Michael Snoyman
maintainer:
- public@pilgrem.com
- michael@snoyman.com
copyright: 2018-2026 FP Complete
github: commercialhaskell/http-download
description: |
  A Haskell library that provides higher-level functions to try to download
  files over HTTP, including verification of content and retries.

extra-source-files:
- CHANGELOG.md
- README.md

dependencies:
- base >=4.10 && < 5
- crypton >= 1.1.0
- http-client
- path
- path-io
- retry
- rio
- rio-prettyprint

ghc-options:
- -Wall

library:
  source-dirs: src
  dependencies:
  - base64-bytestring
  - bytestring
  - conduit
  - conduit-extra
  - crypton-conduit >= 0.3.0
  - directory
  - exceptions
  - filepath
  - http-conduit
  - http-types
  - ram

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - http-download
    - hspec
    - hspec-discover
