name: Unit tests

on:
  pull_request:
  push:
    branches:
    - master
  workflow_dispatch:

# As of 6 August 2023, ubuntu-latest, windows-latest and macos-latest come
# with Stack 2.11.1 and GHC 9.6.2.

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        resolver:
        - stack-ghc-9.2.8.yaml
        - stack-ghc-9.4.5.yaml
        - stack-ghc-9.6.2.yaml
        include:
        - os: windows-latest
          resolver: stack-ghc-9.6.2.yaml
        - os: macos-latest
          resolver: stack-ghc-9.6.2.yaml
    steps:
    - name: Clone project
      uses: actions/checkout@v3
    - name: Cache dependencies on Unix-like OS
      if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
      uses: actions/cache@v3
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.resolver }}
    - name: Cache dependencies on Windows
      if: startsWith(runner.os, 'Windows')
      uses: actions/cache@v3
      with:
        path: |
          ~\AppData\Roaming\stack
          ~\AppData\Local\Programs\stack
        key: ${{ runner.os }}-${{ matrix.resolver }}
    - name: Run tests
      shell: bash
      run: |
        set -ex
        stack --resolver ${{ matrix.resolver }} test --bench --no-run-benchmarks --haddock --no-haddock-deps
